// Regenerates web/firmware.js with the latest release firmware embedded as base64.
// Run after a new firmware release:
//   node tools/gen_firmware_js.mjs

import { writeFileSync } from "node:fs";

const OUT = new URL("../web/firmware.js", import.meta.url);
const REPO = "nOS-Coding/PicoKiller";

async function fetchRelease() {
  const res = await fetch(`https://api.github.com/repos/${REPO}/releases/latest`);
  if (!res.ok) throw new Error(`GitHub API ${res.status}: ${await res.text()}`);
  return res.json();
}

async function fetchAsset(data) {
  const asset = (data.assets || []).find((a) => a.name === data.name);
  if (!asset) throw new Error(`release asset not found: ${data.name}`);
  const res = await fetch(asset.browser_download_url);
  if (!res.ok) throw new Error(`asset fetch ${res.status}: ${data.name}`);
  const buf = Buffer.from(await res.arrayBuffer());
  return buf.toString("base64");
}

const release = await fetchRelease();
const names = ["picokiller-pico.uf2", "picokiller-pico2.uf2"];
const out = [`/* Generated by tools/gen_firmware_js.mjs from ${release.tag_name} (${release.name}). */`,
  `/* Run: node tools/gen_firmware_js.mjs after a firmware release. */`,
  `"use strict";`,
  `window.PICO_FIRMWARE = {`];
for (const name of names) {
  const b64 = await fetchAsset({ ...release, name });
  out.push(`  ${JSON.stringify(name)}: "${b64}",`);
}
out.push(`};`);

writeFileSync(OUT, out.join("\n") + "\n");
const kb = (Buffer.byteLength(out.join("")) / 1024).toFixed(0);
console.log(`wrote ${OUT.pathname} (${kb} KB) from ${release.tag_name}`);
